### PR TITLE
Added unsafe paths and rewrote some paths using glitches

### PR DESCRIPTION
**Pull request by FloSH02**

### CODE REVIEW

**Comment by SiriusAshling** [comment]
Trying to generate a seed creates the following error:
`Error parsing areas.wotw: Failed to parse amount at line 6485: SentryRedirect OR GrenadeRedirect`
Presumably SentryRedirect is not a supported glitch yet

**Comment by FloSH02** [comment]
you are totally right. can i change it without destroying the pull request? 
It would need to be `SentryRedirect=1 OR GrenadeRedirect=1`

**Comment by MunWolf** [comment]
Just make your change and push it to your kii branch, the PR will be updated

**Comment by FloSH02** [comment]
did it!

**Pull request merged**
