### PR TITLE
New shop commands

### PR DESCRIPTION
**Pull request by MunWolf**
Added the new shop commands added in wotw-client dev branch.
Also added _ on a couple of unusued variables to suppress the build warnings (as its deserialization code)
and removed the SpawnLoc struct as it is entirely unused.

### CODE REVIEW

**Comment by MunWolf** [comment]
There is the question, should I split the LockeAndVisible command into 2 different ones?

**Comment by SiriusAshling** [comment]
When trying to generate a seed with the key_hints header, it creates the following error:
`Error generating seed: missing description in item 17|2|1|23                                            in header key_hints.wotwrh`
Presumably the rust parser implementation doesn't mirror the csharp parser implementation?

**Comment by MunWolf** [comment]
hmm interesting, I didn't get that error when I tried it.
but yes Ill need to add that the parameter is optional

**Comment by SiriusAshling** [comment]
seed generation works now oriGlow

Updating the vscode extension parsers now, and someone should playtest a seed probably and look at the Water hint logic

**Comment by SiriusAshling** [comment]
For the documentation, what do visible/locked do exactly?

**Pull request merged**
